function $(id){return document.getElementById(id)}
function login(){if($('user').value==='admin'&&$('pass').value==='admin123'){sessionStorage.setItem('civilAdmin','1');start()}else alert('Invalid demo credentials.')}
function start(){if(sessionStorage.getItem('civilAdmin')==='1'){$('login').classList.add('hidden');$('app').classList.remove('hidden');updateDashboard();renderArticles()}}
function logout(){sessionStorage.removeItem('civilAdmin');location.reload()}
function data(){return JSON.parse(localStorage.getItem('civilNews')||'[]')}
function save(n){localStorage.setItem('civilNews',JSON.stringify(n))}
function showTab(id,btn){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('aside nav button').forEach(x=>x.classList.remove('sel'));if(btn)btn.classList.add('sel');if(id==='articles')renderArticles();if(id==='dashboard')updateDashboard()}
function updateDashboard(){let n=data();$('count').textContent=n.length;$('published').textContent=n.filter(x=>x.status==='Published').length;$('drafts').textContent=n.filter(x=>x.status==='Draft').length;$('recent').innerHTML=n.slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(x=>`<div class="row"><b>${esc(x.title)}</b><span>${x.category} • ${x.status}</span></div>`).join('')}
function renderArticles(){let q=($('adminSearch')?.value||'').toLowerCase();let n=data().filter(x=>(x.title+x.category).toLowerCase().includes(q));$('articleTable').innerHTML=`<table><thead><tr><th>Headline</th><th>Category</th><th>Status</th><th>Date</th><th>Actions</th></tr></thead><tbody>${n.map(x=>`<tr><td><b>${esc(x.title)}</b></td><td>${esc(x.category)}</td><td><span class="pill">${x.status}</span></td><td>${new Date(x.date).toLocaleDateString()}</td><td><button onclick="editArticle(${x.id})">Edit</button> <button class="danger" onclick="archiveArticle(${x.id})">Archive</button></td></tr>`).join('')}</tbody></table>`}
function newArticle(){resetForm();showTab('add',document.querySelectorAll('aside nav button')[2])}
function editArticle(id){let x=data().find(a=>a.id===id);if(!x)return;$('editId').value=x.id;$('title').value=x.title;$('category').value=x.category;$('status').value=x.status;$('summary').value=x.summary;$('content').value=x.content;$('image').value=x.image||'';$('formTitle').textContent='Edit News';showTab('add',document.querySelectorAll('aside nav button')[2])}
function saveArticle(e){e.preventDefault();let n=data(),id=Number($('editId').value),obj={id:id||Date.now(),title:$('title').value,category:$('category').value,status:$('status').value,summary:$('summary').value,content:$('content').value,image:$('image').value,date:new Date().toISOString()};if(id){n=n.map(x=>x.id===id?obj:x)}else n.unshift(obj);save(n);resetForm();updateDashboard();renderArticles();showTab('articles',document.querySelectorAll('aside nav button')[1]);alert('Article saved.')}
function archiveArticle(id){if(confirm('Move this article to archive?')){let n=data().map(x=>x.id===id?{...x,status:'Archived'}:x);save(n);updateDashboard();renderArticles()}}
function resetForm(){['editId','title','summary','content','image'].forEach(id=>$(id).value='');$('status').value='Published';$('category').value='Nepal';$('formTitle').textContent='Add News'}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function saveSettings(e){e.preventDefault();localStorage.setItem('civilSettings',JSON.stringify({company:$('company').value,location:$('location').value,email:$('contactEmail').value,phone:$('phone').value}));alert('Settings saved in this browser.')}
start();
